# -*- coding: utf-8 -*-
"""Mistral_IA_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nilsaes/normalizacion_sales_data.ipynb/blob/main/Mistral_IA_clean.ipynb

# Instalaciones y dependencias
"""

!pip install pandas langchain langchain-experimental tabulate langchain-ollama

"""# *Importamos las librerias*"""

import pandas as pd
import langchain

print("Pandas version:", pd.__version__)
print("LangChain version:", langchain.__version__)
print(" Todo instalado correctamente")

"""# ***Configuramos el API Key***"""

from google.colab import userdata
import os

os.environ["MISTRAL_API_KEY"] = userdata.get("MISTRAL_API_KEY")
print("API Key cargada correctamente")

# ttlUH11iq9d1roD58pA3gOlq4DC0zPet

"""# Instalar Mistral

"""

!pip install langchain-mistralai

from langchain_mistralai import ChatMistralAI

llm = ChatMistralAI(
    model="mistral-small-latest",
    temperature=0
)

respuesta = llm.invoke("Respondé solo esto: ¿estás funcionando?")
print(respuesta.content)

"""# Creacion de agente"""

import pandas as pd

# Cargar tu dataset
dm = pd.read_csv("data_sample.csv")   # o el archivo que estés usando
print(dm.head())

from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_mistralai import ChatMistralAI

# --- Paso 1: Definir el LLM ---
llm = ChatMistralAI(model="mistral-large-latest")

# --- Paso 2: Crear el agente para DataFrame ---
agent_df = create_pandas_dataframe_agent(
    llm,
    dm,   # tu DataFrame de pandas
    prefix="Agente de análisis de ventas",
    verbose=True,
    allow_dangerous_code=True
)

# --- Paso 3: Probar el agente ---
respuesta = agent_df.run("¿Cuál fue el país con más ventas de motocicletas en 2023?")
print(respuesta)

"""# **Cargar el dataset y convertirlo en documentos**"""

# Instalamos librerías necesarias para el agente RAG:
!pip install langchain-mistralai langchain-community faiss-cpu

# Instalamos la librería principal LangChain, que provee las herramientas base
# para construir agentes RAG, manejar prompts, cadenas, retrievers y conectores con LLMs.
!pip install langchain

import pandas as pd
from langchain_core.documents import Document


# --- Cargamos el archivo ---
df = pd.read_csv("data_sample.csv")
print(f"Dataset cargado: {df.shape[0]} filas x {df.shape[1]} columnas")
print(df.head(3))

# --- Convertir cada fila en un Document ---
# Cada Document es como una "página" que el sistema puede buscar
def df_a_documentos(df):
    docs = []
    for idx, fila in df.iterrows():
        # Convierte la fila en texto: "columna: valor"
        texto = "\n".join(f"{col}: {val}" for col, val in fila.items() if pd.notna(val))
        docs.append(Document(page_content=texto, metadata={"fila": idx}))
    return docs

documentos = df_a_documentos(df)
print(f"Documentos creados: {len(documentos)}")
print("\nEjemplo del primero:")
print(documentos[0].page_content)

# Instalamos todas las librerías necesarias para construir el agente RAG:
# - langchain: núcleo principal para manejar prompts, cadenas y retrievers.
# - langchain-community: integraciones adicionales (ej. FAISS).
# - langchain-mistralai: conexión con los modelos de Mistral AI (embeddings y chat).
# - faiss-cpu: motor de búsqueda vectorial rápido para indexar y recuperar documentos.
!pip install langchain langchain-community langchain-mistralai faiss-cpu

"""#Crear el Vector Store (la "memoria buscable")"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_mistralai import MistralAIEmbeddings
from langchain_community.vectorstores import FAISS


# --- Paso 2a: Dividir documentos en chunks ---
# Necesario porque algunos documentos pueden ser muy largos
# Con 25 columnas por fila, cada doc tiene ~500 caracteres → chunk_size=600 es suficiente
splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=50   # overlap evita que se pierda contexto entre chunks
)
chunks = splitter.split_documents(documentos)
print(f"Chunks generados: {len(chunks)}")

# --- Paso 2b: Generar embeddings ---
# Un "embedding" convierte texto en números que representan su significado
# Así FAISS puede comparar preguntas con filas del dataset
embeddings = MistralAIEmbeddings(model="mistral-embed")

# --- Paso 2c: Crear el índice FAISS ---
# Esto puede tardar 1-2 minutos con 2823 filas (hace llamadas a la API)
print("Creando vector store... (puede tardar un poco)")
vectorstore = FAISS.from_documents(chunks, embeddings)

# --- Paso 2d: Crear el retriever ---
# k=6 significa: recuperar las 6 filas más similares a la pregunta
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 6}
)
print("✅ Vector store listo")

# --- Verificación: probá buscar algo manualmente ---
resultados = retriever.invoke("ventas de motocicletas en USA")
print(f"\nResultados de prueba ({len(resultados)} encontrados):")
for r in resultados[:2]:
    print("---")
    print(r.page_content[:200])

"""# Armar la cadena RAG y hacer preguntas"""

!pip install langchain langchain-core

from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# CELDA 4 — Cadena RAG
PROMPT_TEMPLATE = """
Sos un analista de ventas experto. Respondé usando ÚNICAMENTE los datos del contexto.
Si no está en el contexto, decí "No tengo suficientes datos para responder eso."

Contexto:
{context}

Pregunta: {question}

Respuesta:"""

prompt = PromptTemplate(input_variables=["context", "question"], template=PROMPT_TEMPLATE)

def formatear_docs(docs):
    return "\n\n---\n".join(doc.page_content for doc in docs)

cadena_rag = (
    {"context": retriever | formatear_docs, "question": RunnablePassthrough()}
    | prompt
    | llm   # recordá definir tu modelo de lenguaje, ej: ChatMistral
    | StrOutputParser()
)

def consultar(pregunta):
    print(f" {pregunta}")
    print(f"\n {cadena_rag.invoke(pregunta)}")
    print("─" * 50)

print(" Agente RAG listo")

consultar("¿Cuál es el ticket promedio de ventas por país?")
consultar("¿Qué país tiene la mayor cantidad de pedidos en estado Shipped?")
consultar("¿Cuál es la línea de productos con más ventas en cada país?")
consultar("¿Cuál es el precio unitario promedio por línea de producto?")
consultar("¿Cómo evolucionan las ventas mes a mes?")
consultar("¿Qué cliente realizó el pedido con el monto total más alto?")
consultar("¿Cuál es el país con el ticket promedio más alto?")
consultar("¿Cuántos pedidos hay en estado Processing vs Cancelled?")
consultar("¿Cuál es la temporada con más ventas?")# Comentario final para activar el commit de Nilsa
