# -*- coding: utf-8 -*-
"""titanic_multiagent_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKu1m5ku-xBvGRMcYD43cFeWJgljY1vR

Paso 1: Importar Librerías (Celda 1)
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

"""Paso 2: AGENTE 1 - El Normalizador"""

def agente_normalizador_titanic(path_csv):
    print(" [Agente 1] Iniciando limpieza, imputación y codificación...")

    # Leer el archivo crudo
    df = pd.read_csv(path_csv)

    # 1. Limpieza: Eliminar columnas que no ayudan a predecir la supervivencia
    columnas_irrelevantes = ['PassengerId', 'Name', 'Ticket', 'Cabin']
    df = df.drop(columns=columnas_irrelevantes, errors='ignore')

    # 2. Imputación: Rellenar nulos de forma directa y segura
    # Llenamos la Edad (Age) con su mediana
    mediana_edad = df['Age'].median()
    df['Age'] = df['Age'].fillna(mediana_edad)

    # Llenamos el Puerto de embarque (Embarked) con el más común (moda)
    moda_embarked = df['Embarked'].mode()[0]
    df['Embarked'] = df['Embarked'].fillna(moda_embarked)

    # 3. Codificación: Convertir categorías de texto (Sex, Embarked) a columnas numéricas (0 y 1)
    df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

    # 4. Escalado: Normalizar las columnas numéricas para que estén en la misma escala
    scaler = StandardScaler()
    columnas_a_escalar = ['Age', 'SibSp', 'Parch', 'Fare']
    df[columnas_a_escalar] = scaler.fit_transform(df[columnas_a_escalar])

    print(" [Agente 1] Proceso terminado. Enviando 'dataset limpio'.\n")
    return df

"""Paso 3: AGENTE 2 - El Entrenador"""

def agente_entrenador(df, target_column='Survived'):
    print(" [Agente 2] Aplicando validación y entrenando modelo...")

    # Separar características (X) de la variable objetivo (y)
    X = df.drop(columns=[target_column])
    y = df[target_column]

    # Aplicar validación: 80% para entrenar, 20% para evaluar el modelo
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Entrenar el modelo (Random Forest)
    modelo = RandomForestClassifier(random_state=42)
    modelo.fit(X_train, y_train)

    # Realizar predicciones con los datos de prueba
    predicciones = modelo.predict(X_test)

    # Calcular métricas de rendimiento
    acc = accuracy_score(y_test, predicciones)
    reporte = classification_report(y_test, predicciones)

    print(" [Agente 2] Entrenamiento completado. Enviando 'métricas + modelo'.\n")
    return acc, reporte

"""Paso 4: AGENTE 3 - El Comunicador"""

def agente_comunicador(accuracy, reporte_detallado):
    print(" [Agente 3] Traduciendo métricas a lenguaje natural...\n")

    reporte_final = f"""
    ==================================================================
REPORTE DE RESULTADOS: PREDICCIÓN DE SUPERVIVENCIA EN EL TITANIC
    ==================================================================
    ¡Hola! El análisis automatizado del pipeline ha finalizado con éxito.

    Resumen del rendimiento:
    El modelo entrenado por el Agente 2 alcanzó una precisión general (Accuracy)
    del {accuracy * 100:.2f}%. Esto significa que el sistema predice correctamente
    si un pasajero sobrevive o no en {accuracy * 100:.2f} de cada 100 casos analizados.

    Desglose técnico de precisión y recall por clase:
    ------------------------------------------------------------------
    {reporte_detallado}
    ------------------------------------------------------------------
    Conclusión del Agente Comunicador: El modelo demuestra un desempeño sólido
    y el dataset procesado por el Agente 1 no presentó anomalías durante el flujo.
    ==================================================================
    """
    return reporte_final

"""Paso 5: Ejecución del Pipeline completo (La Orquesta)"""

# 1. El Agente 1 toma el archivo crudo y genera el 'dataset limpio'
dataset_procesado = agente_normalizador_titanic('train.csv')

# 2. El Agente 2 toma ese 'dataset limpio' y genera las 'métricas'
precision_modelo, reporte_tecnico = agente_entrenador(dataset_procesado, target_column='Survived')

# 3. El Agente 3 toma las métricas y genera el 'reporte en lenguaje natural'
informe_final = agente_comunicador(precision_modelo, reporte_tecnico)

# Mostramos el resultado en pantalla
print(informe_final)# Modificación para el commit de Nilsa
